name: Nuitka Build

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

    - name: Install Nuitka
      run: pip install nuitka

    - name: Build with Nuitka
      run: |
        python -m nuitka \
          --follow-imports \
          --enable-plugin=pygame \
          --standalone \
          --lto=yes \
          --remove-output \
          main.py

    - name: Rename binary
      run: |
        mv main.bin flappy-bird-linux-$(date +%Y%m%d%H%M)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          flappy-bird-linux-*
          main.dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        # 安装Windows版SDL2依赖
        choco install -y vcpython27 sdl2 sdl2_ttf sdl2_image
        pip install pygame

    - name: Install Nuitka
      run: pip install nuitka

    - name: Build with Nuitka
      run: |
        python -m nuitka ^
          --follow-imports ^
          --enable-plugin=pygame ^
          --standalone ^
          --lto=yes ^
          --windows-icon-from-exe=main.py

    - name: Rename executable
      run: |
        ren main.exe flappy-bird-windows-$(Get-Date -Format "yyyyMMddHHmm").exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          flappy-bird-windows-*.exe
          main.dist/
